version: '3'

services:
  apache:
    container_name: ${PROJECT_NAME}_apache
    build: 
      context: ./apache
      args:
        - WEB_USER=${WEB_USER}
        - WEB_GROUP=${WEB_GROUP}
        - APACHE_ROOT_DIR=${APACHE_ROOT_DIR}
    volumes:
      - ../${CONTAINER_ASSET_FOLDER}/logs/apache:${APACHE_ROOT_DIR}/logs
      - ../public:${APACHE_ROOT_DIR}/htdocs
    ports:
      - ${APACHE_EXPOSED_PORT}:80
    networks:
      public_net:
        ipv4_address: ${APACHE_IP}
    environment:
    - APACHE_EXPOSED_PORT=${APACHE_EXPOSED_PORT}
    - APACHE_ROOT_DIR=${APACHE_ROOT_DIR}
    - PHP_IP=${PHP_IP}
    - PHP_APP_DIR=${PHP_APP_DIR}
    - WEB_USER=${WEB_USER}
    - WEB_GROUP=${WEB_GROUP}

  php-fpm:
    container_name: ${PROJECT_NAME}_php_fpm
    depends_on:
      - apache
      - database
        #      - solr
    build:
      context: ./php-fpm
      args:
      - WEB_USER=${WEB_USER}
      - WEB_GROUP=${WEB_GROUP}
      - PHP_ROOT_DIR=${PHP_ROOT_DIR}
    working_dir: ${PHP_APP_DIR}
    volumes:
      - ..:${PHP_APP_DIR}
      - ../${CONTAINER_ASSET_FOLDER}/logs/php:${PHP_ROOT_DIR}/logs
      - ../${CONTAINER_ASSET_FOLDER}/php-fpm/composer:/root/.composer
      - ${PWD}/../${CONTAINER_ASSET_FOLDER}/php-fpm/.bash_history:/root/.bash_history
    networks:
      public_net:
        ipv4_address: ${PHP_IP}
    dns:
      - 8.8.8.8
    environment:
      - PHP_ROOT_DIR=${PHP_ROOT_DIR}
      - APACHE_IP=${APACHE_IP}
      - APACHE_EXPOSED_PORT=${APACHE_EXPOSED_PORT}
      - WEB_USER=${WEB_USER}
      - WEB_GROUP=${WEB_GROUP}
      - MYSQL_IP=${MYSQL_IP}
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  database:
    container_name: ${PROJECT_NAME}_mysql
    build:
      context: ./database
      args:
        - MYSQL_CONTAINER_USER=${MYSQL_CONTAINER_USER}
        - MYSQL_CONTAINER_GROUP=${MYSQL_CONTAINER_GROUP}
    volumes:
      - ../${CONTAINER_ASSET_FOLDER}/logs/mysql:${MYSQL_LOG_DIR}
      - ../${CONTAINER_ASSET_FOLDER}/database:${MYSQL_DATA_DIR}
    networks:
      public_net:
        ipv4_address: ${MYSQL_IP}
    environment:
      - MYSQL_CONTAINER_USER=${MYSQL_CONTAINER_USER}
      - MYSQL_CONTAINER_GROUP=${MYSQL_CONTAINER_GROUP}
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

        #  solr:
        #    container_name: ${PROJECT_NAME}_solr
        #    build:
        #      context: ./solr
        #    volumes:
        #      - ../data/solr/cores/coreen:/opt/solr/server/solr/coreen
        #      - ../data/solr/cores/corefa:/opt/solr/server/solr/corefa
        #      - ../${CONTAINER_ASSET_FOLDER}/solr/data/coreen:/opt/solr/server/solr/coreen/data
        #      - ../${CONTAINER_ASSET_FOLDER}/solr/data/corefa:/opt/solr/server/solr/corefa/data
        #    networks:
        #      public_net:
        #        ipv4_address: ${SOLR_IP}
        #    ports:
        #      - ${SOLR_EXPOSED_PORT}:8983

networks:
  public_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: ${NETWORK_SUBNET}
